### ISSUE TITLE
"self.vcs" returns None instead of .git for Azure repos 

### ISSUE THREAD

**Issue by sandeeps311** [copier-org/copier#1043]
**Describe the problem**

self.vcs returns None instead of git for Azure repos in template.py

When Im trying to use the template as azure reps it always returns None instead of ".git"

**To Reproduce**

1. Run `copier ...`
2. using the command copier azure_repo_url  local_repo
3. See error -ValueError: Local template must be a directory.

**Logs**
  
Traceback (most recent call last):
  File "C:\Users\SSharma\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\SSharma\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Projects\copier-project\venv\Scripts\copier.exe\__main__.py", line 7, in <module>
  File "C:\Projects\copier-project\venv\lib\site-packages\plumbum\cli\application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "C:\Projects\copier-project\venv\lib\site-packages\plumbum\cli\application.py", line 634, in run
    retcode = inst.main(*tailargs)
  File "C:\Projects\copier-project\venv\lib\site-packages\copier\cli.py", line 71, in _wrapper
    return method(*args, **kwargs)
  File "C:\Projects\copier-project\venv\lib\site-packages\copier\cli.py", line 298, in main
    ).run_copy()
  File "C:\Projects\copier-project\venv\lib\site-packages\copier\main.py", line 620, in run_copy
    src_abspath = self.template_copy_root
  File "C:\Users\SSharma\AppData\Local\Programs\Python\Python310\lib\functools.py", line 970, in __get__
    val = self.func(instance)
  File "C:\Projects\copier-project\venv\lib\site-packages\copier\main.py", line 593, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "C:\Users\SSharma\AppData\Local\Programs\Python\Python310\lib\functools.py", line 970, in __get__
    val = self.func(instance)
  File "C:\Projects\copier-project\venv\lib\site-packages\copier\template.py", line 402, in subdirectory
    return self.config_data.get("subdirectory", "")
  File "C:\Users\SSharma\AppData\Local\Programs\Python\Python310\lib\functools.py", line 970, in __get__
    val = self.func(instance)
  File "C:\Projects\copier-project\venv\lib\site-packages\copier\template.py", line 263, in config_data
    result = filter_config(self._raw_config)[0]
  File "C:\Users\SSharma\AppData\Local\Programs\Python\Python310\lib\functools.py", line 970, in __get__
    val = self.func(instance)
  File "C:\Projects\copier-project\venv\lib\site-packages\copier\template.py", line 222, in _raw_config
    for p in self.local_abspath.glob("copier.*")
  File "C:\Users\SSharma\AppData\Local\Programs\Python\Python310\lib\functools.py", line 970, in __get__
    val = self.func(instance)
  File "C:\Projects\copier-project\venv\lib\site-packages\copier\template.py", line 441, in local_abspath
    raise ValueError("Local template must be a directory.")
ValueError: Local template must be a directory.

<details>

```

```

</details>

**Expected behavior**

It should identify as git repo for azure repos

**Screenshots/screencasts/logs**

**Environment**
 - OS: 
 - Copier version: 
 - Python version:
 - Installation method: 

**Additional context**

**Comment by sisp** [comment]
Is your Azure Git URL an HTTPS or SSH URL? Does it end with `.git`? Copier uses a a few [patterns](https://github.com/copier-org/copier/blob/47f3d59c27094e6f8ef0bc71acc74d88cbf6bb78/copier/vcs.py#L19-L20) to recognize Git URLs. Azure Git is not among the recognized URLs though unlike github.com and gitlab.com.

If you use an HTTPS URL, could you try prefixing it with `git+`? I.e. `git+https://...`.

**Comment by sandeeps311** [comment]
Im using HTTPS Azure git URL . I have added "git+" to URL and it works
Thanks for your help. If you please add this in the documentation that helps to understand patterns of git URLs

**Comment by sisp** [comment]
I've submitted a PR that adds documentation: #1046
