### ISSUE TITLE
Cannot pass yaml as --data cli argument

### ISSUE THREAD

**Issue by svsk417** [copier-org/copier#1108]
**Describe the problem**
I am trying to pass a list as a `--data` cli argument while generating the project like:
```
copier --force --data 'layers=[data, domain]' --vcs-ref HEAD copy <my template dir> <my target dir>
```

Within the copier.yaml file the layers question is defined as follows: 

```
layers: 
  type: yaml
  help: Which layers do you need? 
  default: [data, domain]
  choices:
    data & domain: [data, domain]
    data: [data]
```

**To Reproduce**

1. Run `copier --force --data 'layers=[data, domain]' --vcs-ref HEAD copy <my template dir> <my target dir>`
2. See error

**Logs**

<details>
```
Traceback (most recent call last):
  File "/usr/local/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
  File "/usr/local/lib/python3.10/site-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/usr/local/lib/python3.10/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python3.10/site-packages/copier/cli.py", line 68, in _wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/copier/cli.py", line 295, in main
    ).run_copy()
  File "/usr/local/lib/python3.10/site-packages/copier/main.py", line 697, in run_copy
    src_abspath = self.template_copy_root
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/copier/main.py", line 670, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "/usr/local/lib/python3.10/site-packages/copier/main.py", line 644, in _render_string
    return tpl.render(**self._render_context())
  File "/usr/local/lib/python3.10/site-packages/copier/main.py", line 249, in _render_context
    "answers_file": self.answers_relpath,
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/copier/main.py", line 430, in answers_relpath
    return Path(template.render(**self.answers.combined))
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/copier/main.py", line 385, in answers
    answer = question.parse_answer(result.init[var_name])
  File "/usr/local/lib/python3.10/site-packages/copier/user_data.py", line 420, in parse_answer
    choice_values = {
  File "/usr/local/lib/python3.10/site-packages/copier/user_data.py", line 420, in <setcomp>
    choice_values = {
TypeError: unhashable type: 'list'
```

</details>

**Expected behavior**

**Screenshots/screencasts/logs**

**Environment**
 - OS: Mac
 - Copier version: copier 7.1.0
 - Python version: 3.10
 - Installation method: pip

**Comment by svsk417** [comment]
That was a fast fix! Thank you very much :)
