### ISSUE TITLE
Copier update crashes when template includes secret questions

### ISSUE THREAD

**Issue by staffanlinnaeus** [copier-org/copier#1177]
### Describe the problem

When an answers file is rendered using `{{ _copier_answers|to_nice_yaml -}}`, no questions with `secret: true` will be included.

This causes problems when running `copier update`. If a template has secret questions, they won't be included in the answers file and copier will crash. 

I tried running `copier update --vcs-ref=0.2.0 --data password=somevalue` but the `--data` flag seems to be ignored.

It's possible to work around this by setting the secret question manually in the answers file, but this is obviously not something that you should do.

Tested with Copier 7.2.0 and 8.0.0.

### Example template

To reproduce the problem, create a new template including the following files:

```yaml
# Filename: copier.yml
username:
    type: str
    help: Enter username

password:
    type: str
    secret: true
    help: Enter password
```
```yaml
# Filename: {{ _copier_conf.answers_file }}.jinja
{{ _copier_answers|to_nice_yaml -}}
```
```yaml
# Filename: somefile.yaml.jinja
---
version: 0.1.0 # Example value that can be changed when setting new git tags
username: {{ username }}
password: {{ password }}
```

### To Reproduce

1. Create a project from a template which has secret questions and a rendered answers file (or use the example above).
2. Run `copier update --vcs-ref=<version>`
   OR
   run `copier update --vcs-ref=<version> --data password=somevalue`

### Logs

```console
Updating to template version 0.2.0
Traceback (most recent call last):
  File "/home/username/.local/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/plumbum/cli/application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/cli.py", line 66, in handle_exceptions
    return method(*args, **kwargs)
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/cli.py", line 369, in main
    ).run_update()
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 809, in run_update
    self._apply_update()
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 835, in _apply_update
    old_worker.run_copy()
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 732, in run_copy
    src_abspath = self.template_copy_root
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 716, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 690, in _render_string
    return tpl.render(**self._render_context())
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 297, in _render_context
    "answers_file": self.answers_relpath,
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 476, in answers_relpath
    return Path(template.render(**self.answers.combined))
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/username/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 453, in answers
    raise ValueError(f'Question "{var_name}" is required')
ValueError: Question "password" is required
```

### Expected behavior

1. `copier update` should prompt for any missing answers (much like when specifying an answers file with `copier copy -a`).
2. `copier update` should not ignore answers to secret questions passed with the `--data` flag.

### Operating system

Linux

### Operating system distribution and version

Ubuntu 22.04

### Copier version

7.2.0, 8.0.0

### Python version

Python 3.10.6

### Installation method

pipx+pypi

**Comment by sisp** [comment]
Thanks for the clear problem report, @staffanlinnaeus. :pray:

This bug is a side effect of #962 and #1006. Before, the value of an unanswered question without a default value was `None`. When the update algorithm replays a fresh project using the old template version, it uses the answers from the answers file without promoting and ignoring values from the `--data` switch, and for a secret question there is no answer. So before, `None` was used for a secret question during replay and now an error is raised.

I think we could restore a similar behavior as before for secret questions because there are no answers for them during replay. But instead of using `None` I'd simply not pass those variables to the Jinja context, so they can be checked for using the [`variable is defined` test](https://jinja.palletsprojects.com/en/3.1.x/templates/#jinja-tests.defined) because `None` is ambiguous for JSON/YAML questions.

The rationale for omitting answers of secret questions during replay is that they are typically used in tasks or files that aren't under source control (like `.env.local`), both cases shouldn't be relevant for an update. Both before introducing and after fixing this bug, it was and will be important to handle the case correctly in which the answer to a secret question isn't available, so there would be no conceptual change.

Would this solution work for you, @staffanlinnaeus?

WDYT, @yajo @pawamoy?

**Comment by yajo** [comment]
Hello! Copier 8 has broken many things indeed... on purpose! These corner cases were hidden here and there.

IMHO the easiest solution we can develop for this problem is to ensure that secret questions always have a default value.

That would fix the problem for the future, but for upgrading from old templates, you can temporarily use Copier 7, or you can just issue a `copier recopy` with Copier 8 (this new command is there to help in such situations when the update can't replay for whatever reason) and possibly fix some extra conflicts for this time.

Seems good?

**Comment by sisp** [comment]
Much better than my suggestion, I like it! :+1:

**Comment by staffanlinnaeus** [comment]
Thanks for the quick feedback @sisp and @yajo, much appreciated!

I tested setting a default value for the secret question in our template and now both update and recopy works! For our purposes, this is an acceptable workaround for now.

Again, thank you for your input on this!

**Comment by yajo** [comment]
In general, the default should be "".

If you want to add a random string by default, or something like "super secret password", it's OK too. It's just a template.
