### ISSUE TITLE
Multiple choices with the same value cause an error depending on the order of choices when using `-d` flag

### ISSUE THREAD

**Issue by GytisBraz** [copier-org/copier#1233]
### Describe the problem

Creating a project from a template where there are multiple choices with the same value sometimes raises an error. This happens when prompt answers are passed with the `-d` flag.

### Template

Here is the `copier.yml` file which should suffice:

```yaml
item:
  type: str
  help: Choose an item type
  choices:
  - fruit
  - clothes

item_color:
  type: str
  help: Choose an item color
  choices:
    banana:
      value: yellow
      validator: '{% if item == "fruit" %}{% else %}does not apply{% endif %}'
    tshirt:
      value: yellow
      validator: '{% if item == "clothes" %}{% else %}does not apply{% endif %}'
    apple:
      value: red
      validator: '{% if item == "fruit" %}{% else %}does not apply{% endif %}'
    pants:
      value: red
      validator: '{% if item == "clothes" %}{% else %}does not apply{% endif %}'
```

### To Reproduce

- Run `copier copy ./ ./temp-dir -d 'item=clothes' -d 'item_color=yellow'`
- You will encounter the following error: https://github.com/copier-org/copier/blob/v8.0.0/copier/user_data.py#L457

### Logs

```console
copier copy ./ ./temp-dir -d 'item=clothes' -d 'item_color=yellow'

Traceback (most recent call last):
  File "/Users/gytis/.local/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/plumbum/cli/application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/cli.py", line 66, in handle_exceptions
    return method(*args, **kwargs)
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/cli.py", line 237, in main
    self._worker(
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 732, in run_copy
    src_abspath = self.template_copy_root
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 716, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 690, in _render_string
    return tpl.render(**self._render_context())
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 297, in _render_context
    "answers_file": self.answers_relpath,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 476, in answers_relpath
    return Path(template.render(**self.answers.combined))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 439, in answers
    answer = question.parse_answer(result.init[var_name])
  File "/Users/gytis/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/user_data.py", line 457, in parse_answer
    raise ValueError(f"Invalid choice: {choice.disabled}")
ValueError: Invalid choice: does not apply
```

### Expected behavior

It seems that the second question causes the error because internally the choices are looped over, and the choice `banana` with value `yellow` passes the internal check `if ans == self.cast_answer(choice.value)`. But since the choice is disabled (due to validation failing for `banana` because `item: clothes` is selected), the error is raised.

Since the order matters in this case, `copier copy ./ ./temp-dir -d 'item=fruit' -d 'item_color=yellow'` succeeds without an error, which is a bit confusing 😁 

I would expect the failing command to work, because I'm targeting `item_color=yellow`, which exists, and I'm also targeting `item=clothes`, which should pin-point the exact choice in the second question.

Moreover, just following the prompt (and not passing any values with `-d`) works fine with multiple choices having the same value. So it feels like one should also be able to create a project without following the full prompt (and using `-d` to pass values in).

### Operating system

macOS

### Operating system distribution and version

12.6.2 Monterey

### Copier version

8.0.0

### Python version

3.9.13

### Installation method

pipx+pypi

**Comment by sisp** [comment]
Thanks for your clear and helpful bug report, @GytisBraz. :pray: I've reproduced the problem and submitted a PR that fixes it. See #1235 for more details.

**Comment by GytisBraz** [comment]
Thanks for the quick response and the PR fix @sisp ! 🙇
