### ISSUE TITLE
pydantic 1.10.7- fails on python3.9 for copier 8.1.0

### ISSUE THREAD

**Issue by pwwang** [copier-org/copier#1273]
### Describe the problem

If we have `pydantic` version <= 1.10.7 installed on python3.9, importing `copier` will fail:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/copier/__init__.py", line 6, in <module>
    from .main import *  # noqa: F401,F403
  File "/usr/local/lib/python3.9/dist-packages/copier/main.py", line 78, in <module>
    class Worker:
  File "pydantic/dataclasses.py", line 224, in pydantic.dataclasses.dataclass.wrap
    #
  File "pydantic/dataclasses.py", line 347, in pydantic.dataclasses._add_pydantic_validation_attributes
    # return "(self.x,self.y)".
  File "pydantic/dataclasses.py", line 400, in pydantic.dataclasses.create_pydantic_model_from_dataclass
    exec(txt, globals, ns)
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

### Template

-

### To Reproduce

Make sure your python version is 3.9

```
!python3.9 -m pip install pydantic==1.10.7
!python3.9 -c 'import copier'
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/copier/__init__.py", line 6, in <module>
    from .main import *  # noqa: F401,F403
  File "/usr/local/lib/python3.9/dist-packages/copier/main.py", line 78, in <module>
    class Worker:
  File "pydantic/dataclasses.py", line 224, in pydantic.dataclasses.dataclass.wrap
    #
  File "pydantic/dataclasses.py", line 347, in pydantic.dataclasses._add_pydantic_validation_attributes
    # return "(self.x,self.y)".
  File "pydantic/dataclasses.py", line 400, in pydantic.dataclasses.create_pydantic_model_from_dataclass
    exec(txt, globals, ns)
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

Here is the colab to reproduce it:

https://colab.research.google.com/drive/1YvHWMhEo86vEIKRiGGkSjBvQT2tr5wog?usp=sharing

### Expected behavior

copier to be imported correctly.

### Operating system

Linux

### Operating system distribution and version

 Ubuntu 22.04

### Copier version

8.1.0

### Python version

Python3.9

### Installation method

pip+pypi

### Additional context

We should probably use the conditional version spec for pydantic in pyproject.toml:

https://github.com/copier-org/copier/blob/67f2664b6a9ce50fa6bcf29ccded5353b167c10b/pyproject.toml#L42

```
pydantic = [
  {version = ">1.10.7,<2", python = "<3.10" },
  {version = ">=1.10.2,<2", python = ">=3.10" }
]
```

if we are gonna have a patch release for 8.1 (8.1.1?)

Python3.8 and pedantic versions were not tested. Not sure if it has a different minimal pydantic version requirement.

**Comment by yajo** [comment]
Hi there! Thanks for the issue, but to solve it it seems all you need to do is to bump the pydantic version installed in your venv.

The master branch already has support for Pydantic 2, so that's gonna be the next release.

I hope you understand, thanks!
