### ISSUE TITLE
Validation Error for Integer Placeholder in copier.yml

### ISSUE THREAD

**Issue by b-j-karl** [copier-org/copier#1327]
### Describe the problem

When defining a question in copier.yml with the type set to int, and providing an integer placeholder, a Pydantic ValidationError occurs. The traceback indicates that the placeholder should be of type string, even when the type is set to int.

### Template

A folder named template containing three files:

1. {{_copier_conf.answers_file}}.jinja (Contents below)
``` 
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
{{ _copier_answers|to_nice_yaml -}}
```

2. copier.yml (Contents below)
``` 
example:
  type: int
  help: >
    Enter an integer
  placeholder: 598867978
```

3. test.txt (An empty txt file)

### To Reproduce

Create an empty folder named destination in the directory that the template is in.

1. Run the following commands using Git bash:
```
python -m ensurepip
python -m pip install pip --upgrade
python -m pip install copier --upgrade
python -m pip install pydantic --upgrade

rm destination/.copier-answers.yml

python -m copier copy ./template ./destination --UNSAFE
```

2. Enter an integer when prompted

### Logs

```console
Traceback (most recent call last):
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\copier\__main__.py", line 7, in <module>
    copier_app_run()
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\plumbum\cli\application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\plumbum\cli\application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\copier\cli.py", line 66, in handle_exceptions
    return method(*args, **kwargs)
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\copier\cli.py", line 237, in main
    with self._worker(
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\copier\main.py", line 205, in __exit__
    raise value
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\copier\cli.py", line 244, in main
    worker.run_copy()
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\copier\main.py", line 737, in run_copy
    self._ask()
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\copier\main.py", line 418, in _ask
    question = Question(
  File "C:\XXX\.pyenv\pyenv-win\versions\3.10.8\lib\site-packages\pydantic\_internal\_dataclasses.py", line 124, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Question
placeholder
  Input should be a valid string [type=string_type, input_value=598867978, input_type=int]
    For further information visit https://errors.pydantic.dev/2.3/v/string_type
```

### Expected behavior

I would expected the placeholder for "example" to be parsed as an int instead of a string_type.

### Operating system

Windows

### Operating system distribution and version

Microsoft Windows 10 Enterprise 10.0.19045 Build 19045

### Copier version

copier 8.3.0

### Python version

Python 3.10.8

### Installation method

pip+pypi

### Additional context

When the placeholder value is wrapped in double quotes it is parsed correctly.

For example, the following copier.yml file:
``` 
example:
  type: int
  help: >
    Enter an integer
  placeholder: "598867978"
```
Produces the following .copier-answers file when 598867978 is input:
``` 
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: ./template
example: 598867978
```

Pydantic Version: 2.3.0

**Comment by yajo** [comment]
> I would expected the placeholder for "example" to be parsed as an int instead of a string_type.

No, because other types such as json or yaml would not allow you to put comments in the placeholder.

This is a matter of updating the docs. Thanks for the issue!
