### ISSUE TITLE
Custom `block_start_string` (and others) in `_envops` fail if empty `_templates_suffix` used.

### ISSUE THREAD

**Issue by zakstucke** [copier-org/copier#1410]
### Describe the problem

Love the project!

This is a continuation of #432, it happens when `_templates_suffix: ""` is also used. You can verify this is the cause by removing the `_templates_suffix` line in the below repro, and renaming `hello_world.txt` to `hello_world.txt.jinja`, the below repro will then succeed.

### To Reproduce

`copier.yml`
```yml
_templates_suffix: ""
_exclude:
    - downstream/

_envops:
    block_start_string: "[?"
    block_end_string: "?]"
    variable_start_string: "[<"
    variable_end_string: ">]"    

hello_text:
    type: str
```

`hello_world.txt`
```
[<hello_text>]
```

```
copier copy --trust -d hello_text="Hello, World" . downstream/
```

```
Traceback (most recent call last):
  File "/Users/zak/.local/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
             ^^^^^^^^^^^^^^^^
  File "/venvs/copier/lib/python3.12/site-packages/plumbum/cli/application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/copier/lib/python3.12/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/venvs/copier/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/copier/lib/python3.12/site-packages/copier/cli.py", line 72, in handle_exceptions
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/copier/lib/python3.12/site-packages/copier/cli.py", line 265, in main
    with self._worker(
  File "/venvs/copier/lib/python3.12/site-packages/copier/main.py", line 205, in __exit__
    raise value
  File "/venvs/copier/lib/python3.12/site-packages/copier/cli.py", line 272, in main
    worker.run_copy()
  File "/venvs/copier/lib/python3.12/site-packages/copier/main.py", line 747, in run_copy
    self._render_folder(src_abspath)
  File "/venvs/copier/lib/python3.12/site-packages/copier/main.py", line 642, in _render_folder
    self._render_file(file)
  File "/venvs/copier/lib/python3.12/site-packages/copier/main.py", line 559, in _render_file
    tpl = self.jinja_env.get_template(src_relpath)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/copier/lib/python3.12/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/copier/lib/python3.12/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/copier/lib/python3.12/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/copier/lib/python3.12/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/venvs/copier/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/tmp/copier.yml", line 6, in template
    block_start_string: "[?"
^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: tag name expected
```

### Expected behavior

Custom jinja blocks specified in `_envops` of a `copier.yml` should succeed, but fails when `_templates_suffix: ""` is set.

### Operating system

macOS

### Operating system distribution and version

Sonoma 14.1 (23B74)

### Copier version

copier 9.0.1

### Python version

CPython 3.12

### Installation method

pipx+pypi

**Comment by yajo** [comment]
Hi there! This seems a misconfiguration in your template.

You're overriding [the default value for exclude](https://copier.readthedocs.io/en/stable/configuring/#exclude). By also removing the .jinja suffix, you're telling Copier that `copier.yml` is a file that should be considered for rendering with jinja.

Just add `copier.yml` to exclusions, and it will work.

**Comment by zakstucke** [comment]
Hi @yajo! Forgot to mention that doesn't work, it was the first thing I tried!

Updating the above example `copier.yml` to include itself in the exclusion list like so still fails: (unless I'm missing something?!)

```yaml
_templates_suffix: ""
_exclude:
    - downstream/
    - copier.yml

_envops:
    block_start_string: "[?"
    block_end_string: "?]"
    variable_start_string: "[<"
    variable_end_string: ">]"    

hello_text:
    type: str
```

**Comment by yajo** [comment]
Are you sure the error is exactly the same?

**Comment by zakstucke** [comment]
@yajo yep error is exactly the same, you can reproduce with just the 2 files and command my original text! (obiously adding copier.yml to exclude to verify that doesn't fix).

I'm currently having to hotfix the installed source code to change the defaults to the config I want to get around this, haven't found another workaround!

**Comment by zakstucke** [comment]
@yajo also same error when commenting out `_exclude` entirely, which should also be fine as `copier.yml` is in the default `_exclude`.:

```yaml
_templates_suffix: ""
# _exclude:
#     - downstream/
#     - copier.yml

_envops:
    block_start_string: "[?"
    block_end_string: "?]"
    variable_start_string: "[<"
    variable_end_string: ">]"    

hello_text:
    type: str
```

**Comment by zakstucke** [comment]
@yajo could you re-open this please? As far as I can see this is a valid problem with no available workaround.

**Comment by sisp** [comment]
I can reproduce the problem and will look into it.

**Comment by sisp** [comment]
I found the problem. When the shown `_envops` settings are set in `copier.yml` and `_templates_suffix: ""` while `_subdirectory` is not set or `""`, then Copier treats `copier.yml` as a templated file and attempts to render it, which fails with the reported error because, e.g., the configured `block_start_string` is treated as the start of a Jinja block, which is malformed there.

I think we should exclude `copier.y[a]ml` when no subdirectory is configured and no templates suffix is used. I'll work on a PR to get this fixed.

IMO, we should recommend using a subdirectory because a serious Copier template will likely require some files that are also present in the template project, e.g. a CI config file, and then one ends up with, e.g.,  `.gitlab-ci.yml` and `.gitlab-ci.yml.jinja` &ndash; which is even impossible when no templates suffix is used. I'll open separate issue to discuss recommending the use of  `_subdirectory` or even enforcing it.

**Comment by zakstucke** [comment]
@sisp just a note, excluding `copier.yml` from rendering completely might break `when` statements in questions:

```yaml
foo:
    type: str
    default: ""
    when: "{{ bar }}"
```

Although if `copier` handles these in a special way, might not be an issue!

**Comment by sisp** [comment]
Copier handles Jinja expressions in `copier.yml` separately, so excluding it does not affect templated statements like `when`.

**Comment by sisp** [comment]
I've submitted a PR with a fix: #1440
