### ISSUE TITLE
Copier copy does not create `.copier-answers.yml` file nor adds any reference to the original template (`TypeError: Template not found`)

### ISSUE THREAD

**Issue by guillemrbaiges** [copier-org/copier#1437]
### Describe the problem

Running `copier copy` and answering the copier questions interactively generates a project without `.copier-answers.yml`. Manually adding this file and running `copier update` returns the following error trace (so I assume the project has no info on the original template):

```
Traceback (most recent call last):
  File "/Users/guillem.rossello/opt/anaconda3/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/plumbum/cli/application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/copier/cli.py", line 66, in handle_exceptions
    return method(*args, **kwargs)
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/copier/cli.py", line 363, in main
    self._worker(
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/copier/main.py", line 771, in run_update
    self._check_unsafe("update")
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/copier/main.py", line 230, in _check_unsafe
    if self.template.jinja_extensions:
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/copier/main.py", line 708, in template
    raise TypeError("Template not found")
TypeError: Template not found
```

I haven't been able to find any reference to this issue in the documentation, and as I understand it the `.copier-answers.yml` file should always be generated except when there are no questions or the `--no-input` flag is used.

### Template

I'm afraid the template lives in an internal repo of the company and I can't share it, but this is the content of the `copier.yml` file of the template (and there is no other reference to copier in the project):

```
# CONFIGURATION -------------------------

_subdirectory: project
_templates_suffix: .jinja
_min_copier_version: "8.1.0"

# PROMPT --------------------------------

organization:
  type: str
  help: ...
  placeholder: ...

python_version:
  type: str
  help: Python version you want to use
  default: '3.9'
  choices:
    - '3.11'
    - '3.10'
    - '3.9'
    - '3.8'

gitops_repo:
  type: str
  help: ...
  placeholder: ...

gitops_autocommit:
  type: bool
  help: ...
  default: true
```

### To Reproduce

1. Create a minimal template with that `.copier.yml` file
2. Create a project using `copier copy ...`

### Logs

```console
Traceback (most recent call last):
  File "/Users/guillem.rossello/opt/anaconda3/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/plumbum/cli/application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/copier/cli.py", line 66, in handle_exceptions
    return method(*args, **kwargs)
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/copier/cli.py", line 363, in main
    self._worker(
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/copier/main.py", line 771, in run_update
    self._check_unsafe("update")
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/copier/main.py", line 230, in _check_unsafe
    if self.template.jinja_extensions:
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/Users/guillem.rossello/opt/anaconda3/lib/python3.9/site-packages/copier/main.py", line 708, in template
    raise TypeError("Template not found")
TypeError: Template not found
```

### Expected behavior

The generated project contains a `.copier-answers.yml` file and `copier update` works

### Operating system

macOS

### Operating system distribution and version

macOS Monterey 12.5.1

### Copier version

8.1.0

### Python version

Python 3.9.13

### Installation method

pip+pypi

**Comment by guillemrbaiges** [comment]
Apologies, that is a typo on my side. I'm actually using a `copier.yaml` file, not a `.copier.yaml` file. I actually tried it with both `copier.yaml` and `copier.yml`

**Comment by pawamoy** [comment]
> the .copier-answers.yml file should always be generated

It is not generated, but rather rendered: it still needs to exist in the template, for example as `{{_copier_conf.answers_file}}.jinja` in your `project` folder.

**Comment by guillemrbaiges** [comment]
You're right, I missed this 🤦 Thank you very much!
