### ISSUE TITLE
impossible to update local template

### ISSUE THREAD

**Issue by 12rambau** [copier-org/copier#1484]
### Describe the problem

One of my colleagues reused the pypackage template I created a long time ago and spotted a problem preventing jinja to render the template.

> It's unrelevant for the question itself but for context I forgot to use the `raw` wrapper around an azure pipeline, so jinja is trying to interpret a non existing variable.

I wanted to work loally on my computer to solve the problem. So I run `copier copy --trust ./pypackage test1` which to my understanding is using the local version of pypackage. But it's not. I continue to get the same error: 

> File "/tmp/copier.vcs.clone.ztp6_wqv/package/.azure/unit.yaml.jinja", line 59, in template
> jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'python'

Even worse, when I change something in the unit.yaml.jinja template the error continues to point to the same line even though it's now in line 64. My guess is that there is a chaching mechanism acting under the hood not taking into account my latest modifications. 

Is it a normal behaviour ? 
If it's the case I can I flush this cache and rely exclusively on the files in my local template ? 

### Template

NA

### To Reproduce

NA

### Logs

```console
(pypackage) ldc_user@CDM1PREPVMW102:/mnt/e/WSL/Users/rambap/azure$ copier copy --trust ./pypackage test1
/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/copier/vcs.py:197: DirtyLocalWarning: Dirty template changes included automatically.
  warn(
________   _______  ___  _____  _   __  ___  _____  ____
| ___ \ \ / / ___ \/ _ \/  __ \| | / / / _ \|  __ \|  __\
| |_/ /\ V /| |_/ / /_\ \ /  \/| |/ / / /_\ \ |  \/| |__
|  __/  \ / |  __/|  _  | |    |    \ |  _  | | __ |  __|
| |     | | | |   | | | | \__/\| |\  \| | | | |_\ \| |___
\_|     \_/ \_|   \_| |_/\____/\_| \_/\_| |_/\____/\____/

🎤 The name of the project with LDC azure organisation
   LDC-REP-RemoteSensing
🎤 The name of the python package
   Package skeleton
🎤 The name of the Azure repository
   package-skeleton
🎤 The slug that will be used to name the lib package
   package_skeleton
🎤 The name of the author
   LDC Research repository
🎤 The email of the author
   remote-sensing@ldc.com
🎤 A short description of the project
   The skeleton of a python lib with everything we need.

Copying from template version 0.0.13
    create  .
    create  docs
    create  docs/contribute.md

    create  docs/_template
    create  docs/_template/pypackage-credit.html
    create  docs/conf.py
    create  docs/index.rst
    create  docs/_static
    create  docs/_static/custom.css
    create  docs/_static/ldc.svg

    create  docs/usage.rst
    create  .gitignore
    create  .pre-commit-config.yaml
    create  .copier-answers.yml
    create  noxfile.py

    create  README.md
    create  CONTRIBUTING.md
    create  tests
    create  tests/test_package_skeleton.py
    create  tests/check_warnings.py
    create  tests/__init__.py
    create  tests/conftest.py
    create  tests/data
    create  tests/data/warning_list.txt
    create  package_skeleton
    create  package_skeleton/__init__.py
    create  package_skeleton/py.typed
    create  pyproject.toml
    create  .azure
    create  .azure/publish.yaml
    create  .azure/pypackage_check.yaml
Traceback (most recent call last):
  File "/home/ldc_user/miniconda3/envs/pypackage/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/plumbum/cli/application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/copier/cli.py", line 66, in handle_exceptions
    return method(*args, **kwargs)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/copier/cli.py", line 237, in main
    with self._worker(
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/copier/main.py", line 205, in __exit__
    raise value
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/copier/cli.py", line 244, in main
    worker.run_copy()
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/copier/main.py", line 747, in run_copy
    self._render_folder(src_abspath)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/copier/main.py", line 640, in _render_folder
    self._render_folder(file)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/copier/main.py", line 642, in _render_folder
    self._render_file(file)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/copier/main.py", line 559, in _render_file
    tpl = self.jinja_env.get_template(src_relpath)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/ldc_user/miniconda3/envs/pypackage/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/tmp/copier.vcs.clone.ztp6_wqv/package/.azure/unit.yaml.jinja", line 59, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'python'
```

### Expected behavior

I was expecting it to use local files and take into account latest modifications.

### Operating system

macOS

### Operating system distribution and version

Ubuntu 22.04

### Copier version

8.3.0

### Python version

3.10

### Installation method

pipx+pypi

**Comment by 12rambau** [comment]
I'm dum. 

`--vcs-ref=HEAD` did the trick. Sorry for the noise.
