### ISSUE TITLE
Passing URL without .git suffix fails

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#217]
I'm not sure if this should be considered a bug, or if we should simply not support it and warn users. If the latter, we could maybe improve the error message: 

```console
% copier https://github.com/pawamoy/copier-poetry project    
Traceback (most recent call last):
  File "/home/pawamoy/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/pawamoy/.local/pipx/venvs/copier/lib/python3.8/site-packages/plumbum/cli/application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/pawamoy/.local/pipx/venvs/copier/lib/python3.8/site-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/home/pawamoy/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/cli.py", line 17, in _wrapper
    return method(*args, **kwargs)
  File "/home/pawamoy/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/cli.py", line 158, in main
    self.parent._copy(template_src, destination_path)
  File "/home/pawamoy/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/cli.py", line 108, in _copy
    return copy(
  File "/home/pawamoy/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/main.py", line 128, in copy
    conf = make_config(**locals())
  File "/home/pawamoy/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/config/factory.py", line 118, in make_config
    return ConfigData(**args)
  File "/home/pawamoy/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/config/objects.py", line 88, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConfigData
src_path
  Project template not found. (type=value_error)
```

`vcs.get_repo` returns `None`, and then the Pydantic model complains about `src_path` being `None`.

**Comment by Yajo** [comment]
For now, you should suffix it with `.git` or prefix it with `git+` AFAIK. I guess adding the exception for github and gitlab would be acceptable.
