### ISSUE TITLE
How do migrations work?

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#228]
I don't understand how migrations work.

Here's what I have:

- I have a project generated from a particular template commit
- I then tagged this commit to be 0.1.0 in the template
- I updated my copier answers in the generated project to say it was generated from 0.1.0
- I restructured the template, added a migration on `0.2.0` that moves folders in the `before` stage, and committed and tagged as 0.2.0
- Finally, when I update the generated project, it seems the migration doesn't run? No folder was renamed, no file was moved.

It would be great if the docs could explain in details how migration work, and even better if they could provide practical examples 🙂 

EDIT: actually, the best would be to show a graph of actions, in order, when generating/updating a project, with tasks, migrations, temp dir creation, diff, etc.

**Comment by pawamoy** [comment]
It turns out the migration are not run because the directory in which I'm running `copier update` is not a git repository. I'm not sure to understand why this is required to update it.

I also happen to have subdirectories which *are* git repositories, and it makes the `update` command fail:

```
Traceback (most recent call last):
  File "/home/ldap/mazzucti/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/plumbum/cli/application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/copier/cli.py", line 17, in _wrapper
    return method(*args, **kwargs)
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/copier/cli.py", line 182, in main
    dst_path=destination_path, only_diff=self.only_diff,
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/copier/cli.py", line 121, in _copy
    **kwargs,
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/copier/main.py", line 142, in copy
    update_diff(conf=conf)
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/copier/main.py", line 231, in update_diff
    git("add", ".")
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/plumbum/commands/base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/plumbum/commands/base.py", line 232, in run
    return p.run()
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/plumbum/commands/base.py", line 193, in runner
    return run_proc(p, retcode, timeout)
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/plumbum/commands/processes.py", line 302, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/plumbum/commands/processes.py", line 22, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/ldap/mazzucti/.local/pipx/venvs/copier/lib64/python3.6/site-packages/plumbum/machines/base.py", line 26, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 128
Command line: | /usr/local/bin/git add .
Stderr:       | error: 'test-project-app/' does not have a commit checked out
              | fatal: adding files failed
```

(The line numbers might be wrong because I patched the code with `print` statements to see what was going on)

I fixed it by ignoring the return code of `git add .`: 

```python
git("add", ".", retcode=None)
```

**Comment by Yajo** [comment]
Well, the template *must* be a git repo for migrations to work. That's a requirement because:

1. The place where Copier extracts versions from is git tags.
1. Copier uses an algorithm that tires to detect if a change comes from the template or from the generated subproject, to respect the subproject history as much as possible (that's why we have an `update` command, which works different that re-copying). This algorithm relies heavily on git.

So the problem you're seeing seems to be correct. Just use git for your templates and all will go well. :wink:

**Comment by pawamoy** [comment]
> Just use git for your templates

...and your generated projects! That's what I didn't have 🙂 Or at least, the generated top directory was not a git repo.

I changed the structure of my template anyway, but should the traceback mentioned above arise again, I'll try and send a PR.

Thanks @Yajo !
