### ISSUE TITLE
Generating a project from an Azure Repos URL fails

### ISSUE THREAD

**Issue by tom-blake** [copier-org/copier#284]
I'm trying to generate a project from a template in an Azure Repo using the following command:

`copier copy my-azure-repo-url .`

Where I'm getting `my-azure-repo-url` from the clone option the Azure portal and is of the format `https://my-azure-organisation/my-azure-project/_git/my-repo`

I am seeing the following error:
```No git tags found in template; using HEAD as ref
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\copier.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\plumbum\cli\application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "c:\python38\lib\site-packages\plumbum\cli\application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "c:\python38\lib\site-packages\copier\cli.py", line 38, in _wrapper
    return method(*args, **kwargs)
  File "c:\python38\lib\site-packages\copier\cli.py", line 252, in main
    self.parent._copy(template_src, destination_path)
  File "c:\python38\lib\site-packages\copier\cli.py", line 173, in _copy
    return copy(
  File "c:\python38\lib\site-packages\copier\main.py", line 133, in copy
    conf = make_config(**locals())
  File "c:\python38\lib\site-packages\copier\config\factory.py", line 125, in make_config
    init_args["data_from_asking_user"] = query_user_data(
  File "c:\python38\lib\site-packages\copier\config\user_data.py", line 213, in query_user_data
    answer = prompt(message, type_fn, answer)
  File "c:\python38\lib\site-packages\plumbum\cli\terminal.py", line 135, in prompt
    ans = readline(question).strip()
  File "c:\python38\lib\site-packages\plumbum\cli\terminal.py", line 16, in readline
    sys.stdout.write(message)
  File "c:\python38\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\python38\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\python38\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\python38\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f3a4' in position 104: character maps to <undefined>
```

Unclear if this is a bug or if I'm simply using the wrong command to generate my project from the template in the Azure repo

**Comment by pawamoy** [comment]
My go-to fix for encoding/decoding errors on Windows in to set these environment variables:

```
PYTHONIOENCODING=UTF-8
LANG=en_US.utf-8
LC_ALL=en_US.utf-8
```

It does not always work though, and I'm not sure this is the actual issue here 🙂

**Comment by Yajo** [comment]
Try `git+https://my-azure-organisation/my-azure-project/_git/my-repo` and report results please.

**Comment by tom-blake** [comment]
@Yajo Using the `git+` prefix did the trick! Many thanks
