### ISSUE TITLE
Pressing alt+enter when in a choice question fails

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#307]
The question: https://github.com/Tecnativa/doodba-copier-template/blob/8b4a8cd020cdacc5c14d10d8a0b87c8948bef891/copier.yml#L323-L333

Copier version: 0002cd7

Log: 

```
🎤 Which PostgreSQL version do you want to deploy?
postgres_version? Format: int  (Use arrow keys)
Traceback (most recent call last):
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/questionary/prompt.py", line 102, in prompt
    answer = _filter(answer)
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/config/user_data.py", line 216, in filter_answer
    return cast_answer_type(answer, self.get_cast_fn())
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/config/user_data.py", line 492, in cast_answer_type
    return type_fn(answer)
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/home/yajo/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/plumbum/cli/application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 38, in _wrapper
    return method(*args, **kwargs)
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 306, in main
    self.parent._copy(
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 174, in _copy
    return copy(
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 135, in copy
    conf = make_config(**locals())
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/config/factory.py", line 141, in make_config
    init_args["data_from_asking_user"] = query_user_data(
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/config/user_data.py", line 526, in query_user_data
    return questionary.get_answers()
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/config/user_data.py", line 384, in get_answers
    self.answers_user = prompt(
  File "/var/home/yajo/.local/pipx/venvs/copier/lib64/python3.9/site-packages/questionary/prompt.py", line 104, in prompt
    raise ValueError(
ValueError: Problem processing 'filter' of postgres_version question: invalid literal for int() with base 10: ''
```

**Comment by Yajo** [comment]
Template bug fixed in https://github.com/Tecnativa/doodba-copier-template/commit/97cdd91766a660b2bd8d205f2328cfb4a6e444b3.

It was using different types in the same question, thus it was doomed to failure. Copier 5 swallowed that, but not v6.
