### ISSUE TITLE
Allow to execute when git is not installed

### ISSUE THREAD

**Issue by yajo** [copier-org/copier#312]
Copier has lots of git-related stuff, but it also has features that work without it. It should be a lazy requirement.

**Comment by astrojuanlu** [comment]
Can confirm:

```
root@a620fae20704:/# which git || echo "git is not available"
git is not available
root@a620fae20704:/# copier --version
Traceback (most recent call last):
  File "/usr/local/bin/copier", line 5, in <module>
    from copier.cli import CopierApp
  File "/usr/local/lib/python3.10/site-packages/copier/__init__.py", line 6, in <module>
    from .main import *  # noqa: F401,F403
  File "/usr/local/lib/python3.10/site-packages/copier/main.py", line 23, in <module>
    from plumbum.cmd import git
ImportError: cannot import name 'git' from 'plumbum.cmd' (/usr/local/lib/python3.10/site-packages/plumbum/cmd.py)
```

(For the same reason, `copier /path/to/template /output` doesn't work without `git` installed either)

**Comment by astrojuanlu** [comment]
Gave this a try in gh-1074.
