### ISSUE TITLE
Error on copy and update 

### ISSUE THREAD

**Issue by joao-p-marques** [copier-org/copier#350]
I get an error when generating the project from a template, and also when trying to update:

I am running the version from `master` with the latest updates.

Copy:
```
➤ copier copy https://github.com/Tecnativa/image-template.git .

# ... Answer questions

 identical  .
    create  .copier-answers.image-template.yml
  conflict  .
 Overwrite .? [Y/n] 
Traceback (most recent call last):
  File "/home/jota/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/plumbum/cli/application.py", line 614, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/plumbum/cli/application.py", line 609, in run
    retcode = inst.main(*tailargs)
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 39, in _wrapper
    return method(*args, **kwargs)
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 250, in main
    self.parent._worker(
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 555, in run_copy
    self._render_folder(src_abspath)
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 452, in _render_folder
    self._render_file(file)
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 428, in _render_file
    dst_abspath.write_bytes(new_content)
  File "/usr/lib64/python3.9/pathlib.py", line 1264, in write_bytes
    with self.open(mode='wb') as f:
  File "/usr/lib64/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib64/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
IsADirectoryError: [Errno 21] Is a directory: '/home/jota/PATH_TO_MY_PROJECT'
```

Only the `.copier-answers` file is generated. If, then, I try to commit that and run an update:
```
➤ copier -f -a .copier-answers.image-template.yml
Traceback (most recent call last):
  File "/home/jota/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/plumbum/cli/application.py", line 614, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/plumbum/cli/application.py", line 609, in run
    retcode = inst.main(*tailargs)
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 39, in _wrapper
    return method(*args, **kwargs)
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 292, in main
    self.parent._worker(
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 624, in run_update
    old_worker.run_copy()
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 555, in run_copy
    self._render_folder(src_abspath)
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 452, in _render_folder
    self._render_file(file)
  File "/home/jota/.local/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 428, in _render_file
    dst_abspath.write_bytes(new_content)
  File "/usr/lib64/python3.9/pathlib.py", line 1264, in write_bytes
    with self.open(mode='wb') as f:
  File "/usr/lib64/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib64/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
IsADirectoryError: [Errno 21] Is a directory: '/tmp/copier.main.update_diff.qscg9tjc'
```

**Comment by Yajo** [comment]
Confirmed. Exact command to reproduce:

    copier -fd pytest=false copy https://github.com/Tecnativa/image-template.git .
