### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by KyleKing** [copier-org/copier#441]
**Describe the problem**

I'm running into failures with `copier update`

**Template**

The project is internal and hosted on Gitea, so I, unfortunately, can't share it

**To Reproduce**

1. Run `copier update`
2. See error below

**Logs**

<details>

```
>copier update
Initialized empty Git repository in C:/Users/king.kyle/AppData/Local/Temp/copier.main.update_diff.itkaampw/.git/
Applying new template file: C:\Users\king.kyle\AppData\Local\Temp\copier.main.update_diff.itkaampw\pyproject_cpt-new.toml
ERROR: could not locate "C:\Users\king.kyle\AppData\Local\Temp\copier.main.update_diff.itkaampw\copier-answer.yml"

error: No such remote 'origin'
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\king.kyle\.local\bin\copier.exe\__main__.py", line 7, in <module>
  File "C:\Users\king.kyle\.local\pipx\venvs\copier\lib\site-packages\plumbum\cli\application.py", line 614, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "C:\Users\king.kyle\.local\pipx\venvs\copier\lib\site-packages\plumbum\cli\application.py", line 609, in run
    retcode = inst.main(*tailargs)
  File "C:\Users\king.kyle\.local\pipx\venvs\copier\lib\site-packages\copier\cli.py", line 70, in _wrapper
    return method(*args, **kwargs)
  File "C:\Users\king.kyle\.local\pipx\venvs\copier\lib\site-packages\copier\cli.py", line 335, in main
    self.parent._worker(
  File "C:\Users\king.kyle\.local\pipx\venvs\copier\lib\site-packages\copier\main.py", line 652, in run_update
    old_worker.run_copy()
  File "C:\Users\king.kyle\.local\pipx\venvs\copier\lib\site-packages\copier\main.py", line 587, in run_copy
    self._execute_tasks(
  File "C:\Users\king.kyle\.local\pipx\venvs\copier\lib\site-packages\copier\main.py", line 187, in _execute_tasks
    subprocess.run(task_cmd, shell=use_shell, check=True, env=local.env)
  File "c:\python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'git remote get-url origin' returned non-zero exit status 2.
```

</details>

**Expected behavior**

Expected update to work

**Environment**
 - OS: Windows 10
 - Copier version: I've tried 4.1.0, 5.1.0, and 6.0.0a7
 - Python version: 3.9.5
 - Installation method: pipx

**Additional context**

I'm still troubleshooting this error. I couldn't replicate the problem from a fresh `copier copy ..` and `copier update` for the same template repository. I made sure to clear the temporary clone cache, but the origin error still reappears

**Comment by KyleKing** [comment]
Update: I tested adding `git+` with `copier copy git+http://... .` and that worked? Previously, the link had been the `.git` version

Possibly related to #217

Closing since this appears to be sort of resolvable
