### ISSUE TITLE
bug: Keyboard input is not displayed on screen.

### ISSUE THREAD

**Issue by timcera** [copier-org/copier#443]
**Describe the problem**

At least for types str and int, what you type isn't displayed.  The cursor increments, but nothing shows up.  Also, what you enter is what copier uses for that variable, just that you are typing blind.  No error messages.

Used 'pip install copier' which installed version 5.1.0.

**Template**

Attached a zip file of the template directory.
[project_directory.zip](https://github.com/copier-org/copier/files/7122354/project_directory.zip)

**To Reproduce**

1. Run `copier ...` either as command line of Python script.
2. Answer any str or int prompts and you can't see what you typed.

**Logs**
No errors.

<details>

```

```

</details>

**Expected behavior**

Expected to see what I typed.

**Screenshots/screencasts/logs**

**Environment**
 - OS: Redhat Enterprise Linux, version 7.9
 - Copier version: 5.1.0
 - Python version: 3.8.11
 - Installation method: pip install copier

**Additional context**

**Comment by Yajo** [comment]
Before investigating more, could you check if it still happens in v6.0.0a7?

**Comment by timcera** [comment]
Tried:
pip install --upgrade git+https://github.com/copier-org/copier.git@v6.0.0a7

and got the following error:

Collecting git+https://github.com/copier-org/copier.git@v6.0.0a7
  Cloning https://github.com/copier-org/copier.git (to revision v6.0.0a7) to /tmp/pip-req-build-mhuku9s0
  Running command git clone -q https://github.com/copier-org/copier.git /tmp/pip-req-build-mhuku9s0
  Running command git checkout -q b3860dd274fde886bc7355f6f2ecc1a488f475e3
  Resolved https://github.com/copier-org/copier.git to commit b3860dd274fde886bc7355f6f2ecc1a488f475e3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /beohome/a/ScientificProgramSupport/local/pythons/python3.8.6/bin/python /beohome/a/ScientificProgramSupport/local/pythons/python3.8.6/lib64/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpagw0nzs1                   
         cwd: /tmp/pip-req-build-mhuku9s0                                                                                                         
    Complete output (33 lines):                                                                                                                   
    Traceback (most recent call last):                                                                                                            
      File "/beohome/a/ScientificProgramSupport/local/pythons/python3.8.6/lib64/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>                                                                                                                        
        main()                                                                                                                                    
      File "/beohome/a/ScientificProgramSupport/local/pythons/python3.8.6/lib64/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main                                                                                                                            
        json_out['return_val'] = hook(**hook_input['kwargs'])                                                                                     
      File "/beohome/a/ScientificProgramSupport/local/pythons/python3.8.6/lib64/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel                                                                                                
        return hook(metadata_directory, config_settings)                                                                                          
      File "/tmp/pip-build-env-xtih1yah/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel                                                                                                                                               
        poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)                                                                     
      File "/tmp/pip-build-env-xtih1yah/overlay/lib/python3.8/site-packages/poetry_dynamic_versioning/__init__.py", line 360, in alt_poetry_create
        _state.project(name).version = _get_version(config)                                                                                       
      File "/tmp/pip-build-env-xtih1yah/overlay/lib/python3.8/site-packages/poetry_dynamic_versioning/__init__.py", line 176, in _get_version
        version = Version.from_vcs(
      File "/tmp/pip-build-env-xtih1yah/overlay/lib/python3.8/site-packages/dunamai/__init__.py", line 890, in from_vcs
        return cls._do_vcs_callback(vcs, pattern, latest_tag, tag_dir)
      File "/tmp/pip-build-env-xtih1yah/overlay/lib/python3.8/site-packages/dunamai/__init__.py", line 906, in _do_vcs_callback
        return mapping[vcs](**kwargs)
      File "/tmp/pip-build-env-xtih1yah/overlay/lib/python3.8/site-packages/dunamai/__init__.py", line 500, in from_git
        code, msg = _run_cmd(
      File "/tmp/pip-build-env-xtih1yah/overlay/lib/python3.8/site-packages/dunamai/__init__.py", line 76, in _run_cmd
        raise RuntimeError(
    RuntimeError: The command 'git for-each-ref "refs/tags/**" --merged HEAD --format "%(refname)@{%(objectname)@{%(creatordate:iso-strict)@{%(*committerdate:iso-strict)@{%(taggerdate:iso-strict)"' returned code 129. Output:
    error: unknown option `merged'
    usage: git for-each-ref [options] [<pattern>]
    
        -s, --shell           quote placeholders suitably for shells
        -p, --perl            quote placeholders suitably for perl
        --python              quote placeholders suitably for python
        --tcl                 quote placeholders suitably for tcl
    
        --count <n>           show only <n> matched refs
        --format <format>     format to use for the output
        --sort <key>          field name to sort on
    ----------------------------------------
WARNING: Discarding git+https://github.com/copier-org/copier.git@v6.0.0a7. Command errored out with exit status 1: /beohome/a/ScientificProgramSupport/local/pythons/python3.8.6/bin/python /beohome/a/ScientificProgramSupport/local/pythons/python3.8.6/lib64/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpagw0nzs1 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /beohome/a/ScientificProgramSupport/local/pythons/python3.8.6/bin/python /beohome/a/ScientificProgramSupport/local/pythons/python3.8.6/lib64/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpagw0nzs1 Check the logs for full command output.

**Comment by timcera** [comment]
Was able to install 6.0.0a0 with:

    pip install --upgrade git+https://github.com/copier-org/copier.git@v6.0.0a0

Same problem though...

**Comment by pawamoy** [comment]
Why not just `pip install copier==6.0.0a7`? Or if you want to _upgrade_ to latest prerelease: `pip install -U --pre copier`.

**Comment by timcera** [comment]
Installed 6.0.0a7 and it works!  Thank you!  Closing...
