### ISSUE TITLE
bug: copier stuck with bugged version of template

### ISSUE THREAD

**Issue by esciara** [copier-org/copier#498]
**Describe the problem**

When one makes a mistake in a template resulting in `copier` throwing an exception, even when the template is corrected, `copier` will still use the previous buggy version of the template.

**Template**

Here is the [copier-troubleshoot.zip](https://github.com/copier-org/copier/files/7671475/copier-troubleshoot.zip) file containing a `copier` template to reproduce the problem.

**To Reproduce**

1. Install the stated version of `copier` as described (see **Environment** section)
2. Unzip the sample template in a directory (here, we will use `copier-troubleshoot/`). You will obtain the following tree:
    ```
    copier-troubleshoot
    ├── copier.yaml
    └── project
        ├── [[\ _copier_conf.answers_file\ ]].tmpl
        └── copier_post_generation_task.py
    ```
3. Follow the command lines below to generate a project from the template and setup a git repo for the generated content:
    <details>

    ```bash
    $ cd copier-troubleshoot/
    $ git init
    $ git add .
    $ git commit -m'first commit'
    [main (root-commit) c9f73e2] first commit
    3 files changed, 6 insertions(+)
    create mode 100644 copier.yaml
    create mode 100644 project/[[ _copier_conf.answers_file ]].tmpl
    create mode 100644 project/copier_post_generation_task.py
    $ copier . ../copier-troubleshoot-gen
    No git tags found in template; using HEAD as ref

        create  copier_post_generation_task.py
        create  .copier-answers.yml

    > Running task 1 of 1: python3 copier_post_generation_task.py

    $ pushd ../copier-troubleshoot-gen
    $ git init
    $ git add .
    $ git commit -m'first template generation'
    [main (root-commit) b50a583] first template generation
    2 files changed, 3 insertions(+)
    create mode 100644 .copier-answers.yml
    create mode 100644 copier_post_generation_task.py
    $ popd
    ```
    </details>
4. Change the `copier.yaml` file so that the template generation will fail:
    ```yaml
    # CONFIGURATION -------------------------
    _subdirectory: project
    _tasks:
      - python3 wrong_path/copier_post_generation_task.py
    ```
5. Commit the changes and re-generate the project:
    <details>

    ```bash
    # In the `copier-troubleshoot/` directory
    $ git add .
    $ git commit -m'commit with error'
    [main c20cde9] commit with error
    1 file changed, 1 insertion(+), 1 deletion(-)
    $ copier . ../copier-troubleshoot-gen
    No git tags found in template; using HEAD as ref
    Either c9f73e2 or None is not a PEP 440 valid version.

     identical  copier_post_generation_task.py
      conflict  .copier-answers.yml
     # Press <return> for Yes to overwrite
     Overwrite /your/path/to/copier-troubleshoot-gen/.copier-answers.yml? [Y/n]
         force  .copier-answers.yml

     > Running task 1 of 1: python3 wrong_path/copier_post_generation_task.py
    /opt/homebrew/bin/python3: can't open file '/your/path/to/copier-troubleshoot-gen/wrong_path/copier_post_generation_task.py': [Errno 2] No such file or directory
    Traceback (most recent call last):
      File "[$HOME]/.local/bin/copier", line 8, in <module>
        sys.exit(CopierApp.run())
      File "[$HOME]/.local/pipx/venvs/copier/lib/python3.10/site-packages/plumbum/cli/application.py", line 629, in run
        inst, retcode = subapp.run(argv, exit=False)
      File "[$HOME]/.local/pipx/venvs/copier/lib/python3.10/site-packages/plumbum/cli/application.py", line 624, in run
        retcode = inst.main(*tailargs)
      File "[$HOME]/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/cli.py", line 38, in _wrapper
        return method(*args, **kwargs)
      File "[$HOME]/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/cli.py", line 252, in main
        self.parent._copy(template_src, destination_path)
      File "[$HOME]/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/cli.py", line 173, in _copy
        return copy(
      File "[$HOME]/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 145, in copy
        update_diff(conf=conf)
      File "[$HOME]/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 291, in update_diff
        copy_local(conf)
      File "[$HOME]/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 207, in copy_local
        run_tasks(
      File "[$HOME]/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 484, in run_tasks
        subprocess.run(task_cmd, shell=use_shell, check=True, env=local.env)
      File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command 'python3 wrong_path/copier_post_generation_task.py' returned non-zero exit status 2.
   ```
    </details>
6. Correct the `copier.yaml` file:
    ```yaml
    # CONFIGURATION -------------------------
    _subdirectory: project
    _tasks:
      - python3 copier_post_generation_task.py
    ```
7. Commit the correction and try to re-generate the project (which will fail because of a dirty target repo):
    <details>

    ```bash
    # In the `copier-troubleshoot/` directory
    $ git add .
    $ git commit -m'correct the error'
    [main c15ca61] correct the error
    1 file changed, 1 insertion(+), 1 deletion(-)
    $ copier . ../copier-troubleshoot-gen
    No git tags found in template; using HEAD as ref
    Destination repository is dirty; cannot continue. Please commit or stash your local changes and retry.
    ```
    </details>
8. `copier` refused to generate the project. Commit the changes in the generated project to be able to proceed:
    <details>

    ```bash
    $ pushd ../copier-troubleshoot-gen
    $ git add .
    $ git commit -m'second template generation (generated with error)'
    [main 0b4d8c3] second template generation (generated with error)
    1 file changed, 1 insertion(+), 1 deletion(-)
    $ popd
    ```
    </details>
9. Re-generate the project:
    <details>

    ```bash
    # In the `copier-troubleshoot/` directory
    $ copier . ../copier-troubleshoot-gen
    No git tags found in template; using HEAD as ref
    Either c20cde9 or None is not a PEP 440 valid version.
    /opt/homebrew/bin/python3: can't open file '/private/var/folders/hx/dqkm1p1j2pgf4rtgqlswybt40000gn/T/copier.main.update_diff.c7q8_bm7/wrong_path/copier_post_generation_task.py': [Errno 2] No such file or directory
    Something went wrong. Removing destination folder.
    Traceback (most recent call last):
    # Same traceback as previously
    [..]
    ```
    </details>

The last project generation fails despite the changes that have been made. When looking at the last `copier` command,
one can see that it has used the faulty commit `c20cde9` instead of the latest one with the correction (`c15ca61`).

Looking at the generated project's `.copier-answers.yml` file, the faulty commit is still referenced:
```yaml
# Changes here will be overwritten by Copier
_commit: c20cde9
_src_path: .
```

**Logs**

<details>

```

```

</details>

**Expected behavior**

The latest working version of the template should have been picked up.

**Screenshots/screencasts/logs**

N/A

**Environment**
 - OS: macOS (M1) 12.0.1
 - Copier version: `5.1.0`
 - Python version: `3.10.0`
 - Installation method: `pipx+pypi` (`pipx` was installed with `homebrew`, hence with version `python@3.10`)

**Additional context**

N/A

**Comment by esciara** [comment]
As an extra note/unexpected behavior, I found that in some circonstancesl, during this failure, the message `Something went wrong. Removing destination folder.` was followed by the removal of the `.git` directory in the generated project, or the removal of the whole project. Did not have time to reproduce this one.

**Comment by esciara** [comment]
A workaround consists of removing the `_commit: xxxxxxx` line in the generated project's `.copier-answers.yml` file.

**Comment by Yajo** [comment]
This is an unavoidable side effect of how the smart update algorithm works. It needs to replay last copy, so it knows what has changed. If last version is buggy, the replay will fail and the update also.

In v6 there's the possibility to recopy a project, inheriting last answers but discarding history (and smart update of course). It can help in these cases.

Try it with the last alpha, you should get this sorted out by recopying (using `copier copy` instead of `copier update`).
