### ISSUE TITLE
bug: ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by ap-wtioit** [copier-org/copier#574]
**Describe the problem**
I'm getting the following Error when installing and testing a new docker image with copier installed:
```
...
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/markupsafe/__init__.py)
ERROR: error while running copier (1)
```

It seems the locked versions of jinja2 and MarkupSafe in poetry.lock are no longer compatible.
The currently used jinja version seems to require MarkupSafe < 2.1.0

**Template**
https://github.com/Tecnativa/doodba-copier-template

**To Reproduce**

I guess those should not be necessary (and may take too long)
1. Install fresh copier
2. Run copier (no answers / project needed crashes right at the start)
3. See error

**Logs**

<details>

```
Traceback (most recent call last):
  File "/root/.local/bin/copier", line 5, in <module>
    from copier.cli import CopierApp
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/__init__.py", line 3, in <module>
    from .main import *  # noqa
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 18, in <module>
    from .config import make_config
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/config/__init__.py", line 1, in <module>
    from .factory import make_config  # noqa
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/config/factory.py", line 13, in <module>
    from .user_data import load_answersfile_data, load_config_data, query_user_data
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/config/user_data.py", line 11, in <module>
    from jinja2 import UndefinedError
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/markupsafe/__init__.py)
ERROR: error while running copier (1)
```

</details>

**Expected behavior**

Locked dependencies should be compatible with each other.

**Screenshots/screencasts/logs**

**Environment**
 - OS: Linux
 - Copier version: 5.1.0
 - Python version: 3.7.3
 - Installation method: pipx

**Additional context**
Also see https://github.com/aws/aws-sam-cli/issues/3661 that mentions the same problem were the link to https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0 was posted mentioning the removal of soft_unicode

**Comment by ap-wtioit** [comment]
Testing the following workarround for our systems:
```
pipx install copier
pipx inject copier "MarkupSafe<2.1.0"
```

**Comment by Yajo** [comment]
Seems fixed on master. 

https://github.com/copier-org/copier/blob/95b14a2606201aec2e353bc604c443afea2a154f/poetry.lock#L327

**Comment by ap-wtioit** [comment]
@Yajo when can we get a release that enables installing with pipx for this (i guess that would be version 6.0.0)?

**Comment by Yajo** [comment]
I don't have a release schedule, as I'm maintaining this now on my free time. And I don't plan on publishing any more releases for 5.x, as the main focus is copier 6, which [has evolved a lot already](https://github.com/copier-org/copier/compare/v5.1.0...master).

However, not many issues are left: https://github.com/copier-org/copier/milestone/13

Any help is welcome!

Side note: if it is too important for your company to get a v5.1.1 release that fixes this particular issue, I'm open to offer paid support.

**Comment by tpluscode** [comment]
FWIW, `pipx inject` did not work for me and I'm getting the same issue with `6.0.0a9` :(
