### ISSUE TITLE
On Windows, `py -X -m pipx install copier==6.0.0a9` works where `X` is `3.9` but not `3.10`

### ISSUE THREAD

**Issue by blakeNaccarato** [copier-org/copier#605]
**Describe the problem**

On Windows, `py -X -m pipx install copier==6.0.0a9` works where `X` is `3.9` but not `3.10`. In other words, `pipx` running on Python 3.10 fails to install `copier` due to the following error:

```PowerShell
UnicodeEncodeError: 'charmap' codec can't encode character '\u2502' in position 104: character maps to <undefined>
```

In both Python 3.9 and 3.10, `pip`, `setuptools`, `wheel`, and `pipx` are up to date.

This error is probably a regression related to #284. Perhaps there is a way to tell Windows to use certain encoding like in [this comment](https://github.com/copier-org/copier/issues/284#issuecomment-702576426). However, having to use non-default environment variables to successfully install `copier` on Windows w/ `pipx` in Python 3.10 might still cause enough friction to warrant a second look.

Of course it's still the alpha version, but perhaps there's a quick fix internal to the `copier` project that will sidestep this issue altogether?

**To Reproduce**

1. Be on Windows 10
2. Run `py -3.10 -m pipx install copier==6.0.0a9`

**Logs**

Expand the following to see the **successful** install using `pipx` on Python 3.9 to install `copier==6.0.0a9` on Windows

<details>

```PowerShell
PS C:\Users\Tiana\Blake\Code\gradedoc> py -3.9 -m pip install -U pipx
Requirement already satisfied: pipx in c:\users\tiana\appdata\local\programs\python\python39\lib\site-packages (1.0.0)
Requirement already satisfied: argcomplete>=1.9.4 in c:\users\tiana\appdata\local\programs\python\python39\lib\site-packages (from pipx) (1.12.3)
Requirement already satisfied: colorama>=0.4.4 in c:\users\tiana\appdata\local\programs\python\python39\lib\site-packages (from pipx) (0.4.4)
Requirement already satisfied: userpath>=1.6.0 in c:\users\tiana\appdata\local\programs\python\python39\lib\site-packages (from pipx) (1.7.0)
Requirement already satisfied: packaging>=20.0 in c:\users\tiana\appdata\local\programs\python\python39\lib\site-packages (from pipx) (20.9)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\tiana\appdata\local\programs\python\python39\lib\site-packages (from packaging>=20.0->pipx) (2.4.7)
Requirement already satisfied: click in c:\users\tiana\appdata\local\programs\python\python39\lib\site-packages (from userpath>=1.6.0->pipx) (7.1.2)
PS C:\Users\Tiana\Blake\Code\gradedoc> py -3.10 -m pip install -U pipx
Requirement already satisfied: pipx in c:\users\tiana\appdata\local\programs\python\python310\lib\site-packages (1.0.0)
Requirement already satisfied: userpath>=1.6.0 in c:\users\tiana\appdata\local\programs\python\python310\lib\site-packages (from pipx) (1.8.0)
Requirement already satisfied: colorama>=0.4.4 in c:\users\tiana\appdata\local\programs\python\python310\lib\site-packages (from pipx) (0.4.4)
Requirement already satisfied: argcomplete>=1.9.4 in c:\users\tiana\appdata\local\programs\python\python310\lib\site-packages (from pipx) (2.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\tiana\appdata\local\programs\python\python310\lib\site-packages (from pipx) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\tiana\appdata\local\programs\python\python310\lib\site-packages (from packaging>=20.0->pipx) (3.0.7)
Requirement already satisfied: click in c:\users\tiana\appdata\local\programs\python\python310\lib\site-packages 
(from userpath>=1.6.0->pipx) (8.0.4)
PS C:\Users\Tiana\Blake\Code\gradedoc> py -3.9 -m pipx install copier==6.0.0a9
  installed package copier 6.0.0a9, installed using Python 3.9.7
  These apps are now globally available
    - copier.exe
done! ✨ 🌟 ✨
```

</details>

Expand the following to see the **failed** install using `pipx` on Python 3.10 to install `copier==6.0.0a9` on Windows.

<details>

```PowerShell
PS C:\Users\Tiana\Blake\Code\gradedoc> py -3.10 -m pipx install copier==6.0.0a9

Traceback (most recent call last):
  File "C:\Users\Tiana\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main   
    return _run_code(code, main_globals, None,
  File "C:\Users\Tiana\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tiana\AppData\Local\Programs\Python\Python310\lib\site-packages\pipx\__main__.py", line 14, in <module>
    sys.exit(cli())
  File "C:\Users\Tiana\AppData\Local\Programs\Python\Python310\lib\site-packages\pipx\main.py", line 779, in cli 
    return run_pipx_command(parsed_pipx_args)
  File "C:\Users\Tiana\AppData\Local\Programs\Python\Python310\lib\site-packages\pipx\main.py", line 202, in run_pipx_command
    return commands.install(
  File "C:\Users\Tiana\AppData\Local\Programs\Python\Python310\lib\site-packages\pipx\commands\install.py", line 
60, in install
    venv.install_package(
  File "C:\Users\Tiana\AppData\Local\Programs\Python\Python310\lib\site-packages\pipx\venv.py", line 238, in install_package
    subprocess_post_check_handle_pip_error(pip_process)
  File "C:\Users\Tiana\AppData\Local\Programs\Python\Python310\lib\site-packages\pipx\util.py", line 349, in subprocess_post_check_handle_pip_error
    print(completed_process.stderr, file=pip_error_fh, end="")
  File "C:\Users\Tiana\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode      
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2502' in position 104: character maps to <undefined>
```

</details>

**Expected behavior**

Install should be successful regardless of whether the global Python version the `pipx` package is installed in is 3.9 or 3.10.

**Environment**
 - OS: Windows 10
 - Copier version: 6.0.0a9
 - Python version: 3.10
 - Installation method: pipx+pypi

**Comment by pawamoy** [comment]
Is Copier really concerned though? It's the installation that fails, not the use of Copier. This issue should be opened on pipx instead?

Also, yeah another env var to try: `PYTHONUTF8=1`.

**Comment by blakeNaccarato** [comment]
Hmm, it looks like it's better for me to add to the discussion over at pypa/pipx#819. Sorry for the false alarm. I wasn't sure if `pipx` was touching one of your files and failing out due to an encoding error, or if this is solely due to `pipx`. I'll close this under the assumption that the ball is squarely in `pipx`'s court.

**Comment by blakeNaccarato** [comment]
Okay so it looks like running `py -3.10 -m pipx run --spec git+https://github.com/pypa/pipx.git@main pipx install copier==6.0.0a9` "fails successfully". The `charmap` error above triggers when a `pipx` install fails for any reason, and also conceals the true nature of the issue.

I will open another issue about it when I find some free time to properly document the issue. For now I will just present the output of it below. It seems that `pip` can't find a suitable wheel for `iteration_utilities` and tries to build it instead, but when Microsoft C++ Build Tools are not found (as would be the case in a non-developer machine), it fails out.

```PowerShell
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\Tiana\.local\pipx\logs\cmd_2022-03-14_18.56.40_pip_errors.log

pip failed to build package:
    iteration_utilities

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    error: legacy-install-failure

Error installing copier from spec 'copier==6.0.0a9'.
``
