### ISSUE TITLE
cannot import name 'environmentfilter' from 'jinja2.filters'

### ISSUE THREAD

**Issue by tpluscode** [copier-org/copier#638]
**Describe the problem**

Does not work on fresh install 🤷 

**Template**

**To Reproduce**

1. Install copier
2. `copier -a .copier-github.yaml copy https://github.com/tpluscode/github-copier-template.git .` 

**Logs**

<details>

```
Traceback (most recent call last):
  File "/Users/tplus/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/plumbum/cli/application.py", line 629, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/plumbum/cli/application.py", line 624, in run
    retcode = inst.main(*tailargs)
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/cli.py", line 70, in _wrapper
    return method(*args, **kwargs)
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/cli.py", line 293, in main
    self.parent._worker(
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 580, in run_copy
    src_abspath = self.template_copy_root
  File "/Users/tplus/.pyenv/versions/3.9.5/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 550, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 523, in _render_string
    tpl = self.jinja_env.from_string(string)
  File "/Users/tplus/.pyenv/versions/3.9.5/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/main.py", line 386, in jinja_env
    env = SandboxedEnvironment(
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/sandbox.py", line 253, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2_ansible_filters/__init__.py", line 15, in <module>
    from jinja2_ansible_filters.core_filters import FilterModule
  File "/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2_ansible_filters/core_filters.py", line 37, in <module>
    from jinja2.filters import environmentfilter, do_groupby as _do_groupby
ImportError: cannot import name 'environmentfilter' from 'jinja2.filters' (/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/jinja2/filters.py)
```

</details>

**Environment**
 - OS: macOS Big Sur
 - Copier version: 6.0.0a9
 - Python version: 3.9.5
 - Installation method: pipx

**Comment by Yajo** [comment]
Oh just install from git master. I didn't release the fix yet to pypi. Gotta publish a new alpha.
