### ISSUE TITLE
copier 6.0.0 is no longer working without a terminal

### ISSUE THREAD

**Issue by bigbear3001** [copier-org/copier#666]
**Describe the problem**

We are running copier in our CI systems in daily jobs. This was working ok with 5.1.0. With 6.0.0 we get the following error when running our CI jobs:
```
...
Warning: Input is not a terminal (fd=0).
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 251, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/lib/python3.7/selectors.py", line 192, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '0 is not registered'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/prompt_toolkit/input/vt100.py", line 176, in _attached_input
    loop.add_reader(fd, callback_wrapper)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 324, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 254, in _add_reader
    (handle, None))
  File "/usr/lib/python3.7/selectors.py", line 359, in register
    self._selector.register(key.fd, poller_events)
PermissionError: [Errno 1] Operation not permitted
During handling of the above exception, another exception occurred:
...
ERROR: error while running copier (1)
```

**Template**

https://github.com/tecnativa/doodba-copier-template

**To Reproduce**

1. Run copier inside of docker without `-ti` (Terminal)

**Logs**

<details>

```
/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/template.py:135: OldTemplateWarning: This template was designed for Copier 4.1.0, but your version of Copier is 6.0.0. You could find some incompatibilities.
  OldTemplateWarning,
/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/template.py:265: FutureWarning: On future releases, Copier will switch to standard Jinja defaults and this template will not work unless updated.
  FutureWarning,
Make sure Git >= 2.24 is installed to improve updates.
Warning: Input is not a terminal (fd=0).
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 251, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/lib/python3.7/selectors.py", line 192, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '0 is not registered'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/prompt_toolkit/input/vt100.py", line 176, in _attached_input
    loop.add_reader(fd, callback_wrapper)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 324, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 254, in _add_reader
    (handle, None))
  File "/usr/lib/python3.7/selectors.py", line 359, in register
    self._selector.register(key.fd, poller_events)
PermissionError: [Errno 1] Operation not permitted
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/cli/application.py", line 629, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/plumbum/cli/application.py", line 624, in run
    retcode = inst.main(*tailargs)
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/cli.py", line 71, in _wrapper
    return method(*args, **kwargs)
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/cli.py", line 337, in main
    dst_path=destination_path,
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 727, in run_update
    self.run_copy()
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 596, in run_copy
    src_abspath = self.template_copy_root
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/backports/cached_property/__init__.py", line 80, in __get__
    val = self.func(instance)
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 569, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 543, in _render_string
    return tpl.render(**self._render_context())
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 208, in _render_context
    **self.answers.combined,
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/backports/cached_property/__init__.py", line 80, in __get__
    val = self.func(instance)
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/copier/main.py", line 352, in answers
    [question.get_questionary_structure()], answers=result.combined
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/questionary/prompt.py", line 194, in unsafe_prompt
    answer = question.unsafe_ask(patch_stdout)
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/questionary/question.py", line 92, in unsafe_ask
    return self.application.run()
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 940, in run
    handle_sigint=handle_sigint,
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 855, in run_async
    return await _run_async2()
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 825, in _run_async2
    result = await _run_async()
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 741, in _run_async
    read_from_input
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/root/.local/pipx/venvs/copier/lib/python3.7/site-packages/prompt_toolkit/input/vt100.py", line 185, in _attached_input
    raise EOFError
EOFError
Initialized empty Git repository in /tmp/copier.main.update_diff.iou25_q9/.git/
pre-commit installed at .git/hooks/pre-commit
Initialized empty Git repository in /tmp/copier.main.recopy_diff.4rqje6mb/.git/
pre-commit installed at .git/hooks/pre-commit
ERROR: error while running copier (1)
```

</details>

**Expected behavior**

In 5.1.0 copier was runnable with all answers taken from the prevoius anser file (.copier-answers.yml) without a terminal attached. 

**Screenshots/screencasts/logs**

**Environment**
 - OS: Linux (Ubuntu 20.04 LTS, docker)
 - Copier version: copier 6.0.0
 - Python version: 3.7
 - Installation method: pipx+pypi

**Additional context**

We are running copier on gitlab CI with docker without a terminal attached.

**Comment by yajo** [comment]
What command are you running?

**Comment by yajo** [comment]
Then you accidentally found out you were not using it properly 😁.

That's the interactive mode. Try `copier -f` for automatic mode.
