### ISSUE TITLE
copier generation for https github link fails

### ISSUE THREAD

**Issue by MaciejPatro** [copier-org/copier#706]
**Describe the problem**
Using copier with `https` link to github fails:

```bash
copier https://github.com/MaciejPatro/copier-cpp-cmake .
```
results in:
```
ValueError: Local template must be a directory.
```

while 

```bash
copier git@github.com:MaciejPatro/copier-cpp-cmake.git .
```

Correctly allows to generate a template. Is this an expected behaviour?

**Logs**
<details>

```
Traceback (most recent call last):
  File "/home/pmac/miniconda3/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/pmac/miniconda3/lib/python3.8/site-packages/plumbum/cli/application.py", line 629, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/pmac/miniconda3/lib/python3.8/site-packages/plumbum/cli/application.py", line 624, in run
    retcode = inst.main(*tailargs)
  File "/home/pmac/miniconda3/lib/python3.8/site-packages/copier/cli.py", line 71, in _wrapper
    return method(*args, **kwargs)
  File "/home/pmac/miniconda3/lib/python3.8/site-packages/copier/cli.py", line 294, in main
    self.parent._worker(
  File "/home/pmac/miniconda3/lib/python3.8/site-packages/copier/main.py", line 597, in run_copy
    src_abspath = self.template_copy_root
  File "/home/pmac/miniconda3/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/pmac/miniconda3/lib/python3.8/site-packages/copier/main.py", line 570, in template_copy_root
    subdir = self._render_string(self.template.subdirectory) or ""
  File "/home/pmac/miniconda3/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/pmac/miniconda3/lib/python3.8/site-packages/copier/template.py", line 395, in subdirectory
    return self.config_data.get("subdirectory", "")
  File "/home/pmac/miniconda3/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/pmac/miniconda3/lib/python3.8/site-packages/copier/template.py", line 230, in config_data
    result = filter_config(self._raw_config)[0]
  File "/home/pmac/miniconda3/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/pmac/miniconda3/lib/python3.8/site-packages/copier/template.py", line 189, in _raw_config
    for p in self.local_abspath.glob("copier.*")
  File "/home/pmac/miniconda3/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/pmac/miniconda3/lib/python3.8/site-packages/copier/template.py", line 443, in local_abspath
    raise ValueError("Local template must be a directory.")
ValueError: Local template must be a directory.
```

</details>

**Environment**
 - OS: ubuntu
 - Copier version: `6.1.0`
 - Python version: `3.8`

**Comment by pawamoy** [comment]
Duplicate, already fixed by https://github.com/copier-org/copier/pull/677 🙂 Waiting for a release I suppose.

**Comment by MaciejPatro** [comment]
sorry - I've missed it!

**Comment by pawamoy** [comment]
No problem, thank you for the report anyway 😄
